title: "Go でデバッガを自作する"
summary: "本の紹介文テストテスト"
topics: ["go", "debugger"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - introduction
  - setup
  - continue
  - ptrace
