title: "Go でデバッガを自作する"
summary: "普段開発しているときにデバッガを使用する人は多いと思いますが、その仕組みを理解している方は多くないのではないでしょうか。本書では、Go で簡単なデバッガを自作する方法を解説しています。読者がデバッガの仕組みを理解し、意欲のある方は自作できることを目的としています。\n\n※ 2024年11月の時点では、本書は作成中になります。\n※ 未完成のため、各章の内容が変わる可能性もあるのでご注意ください。"
topics: ["go", "debugger"] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - introduction
  - setup
  - continue
  - ptrace
  - command
  - breakpoint-memory-1
  - breakpoint-memory-2
  - address-to-source-code
  - breakpoint-source
  - stepping
  - conclusion
